"""Add event_vendors relationship

Revision ID: 085bee26298a
Revises: 43384c236c87
Create Date: 2026-01-11 00:11:06.330134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085bee26298a'
down_revision = '43384c236c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_vendors',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_vendors')
    # ### end Alembic commands ###
