"""update user model with notifications

Revision ID: 0ae8d08c7d0e
Revises: d777b64fef48
Create Date: 2026-01-10 18:56:49.158267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae8d08c7d0e'
down_revision = 'd777b64fef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_stock', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_sales', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_email')
        batch_op.drop_column('notify_sales')
        batch_op.drop_column('notify_stock')

    # ### end Alembic commands ###
