"""updated user model for password hashing

Revision ID: 2e0f3e743d75
Revises: e796401eda30
Create Date: 2025-12-28 00:58:39.724566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0f3e743d75'
down_revision = 'e796401eda30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashiers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('access_pin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('kra_pin')
        batch_op.drop_column('settlement_phone')
        batch_op.drop_column('commission_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('settlement_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kra_pin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('contact_phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('cashiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_pin', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
