"""Update wallet models

Revision ID: 43384c236c87
Revises: ca9e7a610fe0
Create Date: 2026-01-10 23:29:16.548076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43384c236c87'
down_revision = 'ca9e7a610fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt')

    # ### end Alembic commands ###
