"""Add status and business permit to users

Revision ID: 62615e6fbef9
Revises: 085bee26298a
Create Date: 2026-01-11 01:17:02.121479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62615e6fbef9'
down_revision = '085bee26298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_permit_no', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('business_permit_no')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
