"""Added mpesa_payments table

Revision ID: da955402f133
Revises: 2e0f3e743d75
Create Date: 2025-12-29 15:48:23.530249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da955402f133'
down_revision = '2e0f3e743d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=50), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=False),
    sa.Column('result_code', sa.Integer(), nullable=False),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('transaction_date', sa.String(length=20), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpesa_payments')
    # ### end Alembic commands ###
